### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by lastmjs** [okgrow/merge-graphql-schemas#124]
By the way, this repo is amazing, and I believe offers a clean solution to multiple issues that I was making custom solutions to when working with Prisma. Thank you! I think this is a simple bug. I've got the following three schemas I'm trying to merge:

```graphql
# datamodel.graphql
directive @userOwns(field: String) on FIELD | FIELD_DEFINITION

type User {
    id: ID! @unique
    createdAt: DateTime!
    updatedAt: DateTime!
    email: String! @unique @userOwns(field: "id")
    password: String!
}
```

```graphql
# dataops.graphql
directive @authenticated on FIELD | FIELD_DEFINITION

type Mutation {
    createUser(data: UserCreateInput!): User! @authenticated
}
```

```graphql
# prisma.graphql
# THIS FILE HAS BEEN AUTO-GENERATED BY "PRISMA DEPLOY"
# DO NOT EDIT THIS FILE DIRECTLY

#
# Model Types
#

type User implements Node {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  email: String!
  password: String!
}


#
# Other Types
#

type AggregateUser {
  count: Int!
}

type BatchPayload {
  """
  The number of nodes that have been affected by the Batch operation.
  """
  count: Long!
}

scalar DateTime

"""
The `Long` scalar type represents non-fractional signed whole numeric values.
Long can represent values between -(2^63) and 2^63 - 1.
"""
scalar Long

type Mutation {
  createUser(data: UserCreateInput!): User!
  updateUser(data: UserUpdateInput!, where: UserWhereUniqueInput!): User
  deleteUser(where: UserWhereUniqueInput!): User
  upsertUser(where: UserWhereUniqueInput!, create: UserCreateInput!, update: UserUpdateInput!): User!
  updateManyUsers(data: UserUpdateInput!, where: UserWhereInput!): BatchPayload!
  deleteManyUsers(where: UserWhereInput!): BatchPayload!
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
}

"""
An object with an ID
"""
interface Node {
  """
  The id of the object.
  """
  id: ID!
}

"""
Information about pagination in a connection.
"""
type PageInfo {
  """
  When paginating forwards, are there more items?
  """
  hasNextPage: Boolean!
  """
  When paginating backwards, are there more items?
  """
  hasPreviousPage: Boolean!
  """
  When paginating backwards, the cursor to continue.
  """
  startCursor: String
  """
  When paginating forwards, the cursor to continue.
  """
  endCursor: String
}

type Query {
  users(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User]!
  user(where: UserWhereUniqueInput!): User
  usersConnection(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): UserConnection!
  """
  Fetches an object given its ID
  """
  node("""
  The ID of an object
  """
  id: ID!): Node
}

type Subscription {
  user(where: UserSubscriptionWhereInput): UserSubscriptionPayload
}

"""
A connection to a list of items.
"""
type UserConnection {
  """
  Information to aid in pagination.
  """
  pageInfo: PageInfo!
  """
  A list of edges.
  """
  edges: [UserEdge]!
  aggregate: AggregateUser!
}

input UserCreateInput {
  email: String!
  password: String!
}

"""
An edge in a connection.
"""
type UserEdge {
  """
  The item at the end of the edge.
  """
  node: User!
  """
  A cursor for use in pagination.
  """
  cursor: String!
}

enum UserOrderByInput {
  id_ASC
  id_DESC
  createdAt_ASC
  createdAt_DESC
  updatedAt_ASC
  updatedAt_DESC
  email_ASC
  email_DESC
  password_ASC
  password_DESC
}

type UserPreviousValues {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  email: String!
  password: String!
}

type UserSubscriptionPayload {
  mutation: MutationType!
  node: User
  updatedFields: [String!]
  previousValues: UserPreviousValues
}

input UserSubscriptionWhereInput {
  """
  Logical AND on all given filters.
  """
  AND: [UserSubscriptionWhereInput!]
  """
  Logical OR on all given filters.
  """
  OR: [UserSubscriptionWhereInput!]
  """
  The subscription event gets dispatched when it's listed in mutation_in
  """
  mutation_in: [MutationType!]
  """
  The subscription event gets only dispatched when one of the updated fields names is included in this list
  """
  updatedFields_contains: String
  """
  The subscription event gets only dispatched when all of the field names included in this list have been updated
  """
  updatedFields_contains_every: [String!]
  """
  The subscription event gets only dispatched when some of the field names included in this list have been updated
  """
  updatedFields_contains_some: [String!]
  node: UserWhereInput
}

input UserUpdateInput {
  email: String
  password: String
}

input UserWhereInput {
  """
  Logical AND on all given filters.
  """
  AND: [UserWhereInput!]
  """
  Logical OR on all given filters.
  """
  OR: [UserWhereInput!]
  id: ID
  """
  All values that are not equal to given value.
  """
  id_not: ID
  """
  All values that are contained in given list.
  """
  id_in: [ID!]
  """
  All values that are not contained in given list.
  """
  id_not_in: [ID!]
  """
  All values less than the given value.
  """
  id_lt: ID
  """
  All values less than or equal the given value.
  """
  id_lte: ID
  """
  All values greater than the given value.
  """
  id_gt: ID
  """
  All values greater than or equal the given value.
  """
  id_gte: ID
  """
  All values containing the given string.
  """
  id_contains: ID
  """
  All values not containing the given string.
  """
  id_not_contains: ID
  """
  All values starting with the given string.
  """
  id_starts_with: ID
  """
  All values not starting with the given string.
  """
  id_not_starts_with: ID
  """
  All values ending with the given string.
  """
  id_ends_with: ID
  """
  All values not ending with the given string.
  """
  id_not_ends_with: ID
  createdAt: DateTime
  """
  All values that are not equal to given value.
  """
  createdAt_not: DateTime
  """
  All values that are contained in given list.
  """
  createdAt_in: [DateTime!]
  """
  All values that are not contained in given list.
  """
  createdAt_not_in: [DateTime!]
  """
  All values less than the given value.
  """
  createdAt_lt: DateTime
  """
  All values less than or equal the given value.
  """
  createdAt_lte: DateTime
  """
  All values greater than the given value.
  """
  createdAt_gt: DateTime
  """
  All values greater than or equal the given value.
  """
  createdAt_gte: DateTime
  updatedAt: DateTime
  """
  All values that are not equal to given value.
  """
  updatedAt_not: DateTime
  """
  All values that are contained in given list.
  """
  updatedAt_in: [DateTime!]
  """
  All values that are not contained in given list.
  """
  updatedAt_not_in: [DateTime!]
  """
  All values less than the given value.
  """
  updatedAt_lt: DateTime
  """
  All values less than or equal the given value.
  """
  updatedAt_lte: DateTime
  """
  All values greater than the given value.
  """
  updatedAt_gt: DateTime
  """
  All values greater than or equal the given value.
  """
  updatedAt_gte: DateTime
  email: String
  """
  All values that are not equal to given value.
  """
  email_not: String
  """
  All values that are contained in given list.
  """
  email_in: [String!]
  """
  All values that are not contained in given list.
  """
  email_not_in: [String!]
  """
  All values less than the given value.
  """
  email_lt: String
  """
  All values less than or equal the given value.
  """
  email_lte: String
  """
  All values greater than the given value.
  """
  email_gt: String
  """
  All values greater than or equal the given value.
  """
  email_gte: String
  """
  All values containing the given string.
  """
  email_contains: String
  """
  All values not containing the given string.
  """
  email_not_contains: String
  """
  All values starting with the given string.
  """
  email_starts_with: String
  """
  All values not starting with the given string.
  """
  email_not_starts_with: String
  """
  All values ending with the given string.
  """
  email_ends_with: String
  """
  All values not ending with the given string.
  """
  email_not_ends_with: String
  password: String
  """
  All values that are not equal to given value.
  """
  password_not: String
  """
  All values that are contained in given list.
  """
  password_in: [String!]
  """
  All values that are not contained in given list.
  """
  password_not_in: [String!]
  """
  All values less than the given value.
  """
  password_lt: String
  """
  All values less than or equal the given value.
  """
  password_lte: String
  """
  All values greater than the given value.
  """
  password_gt: String
  """
  All values greater than or equal the given value.
  """
  password_gte: String
  """
  All values containing the given string.
  """
  password_contains: String
  """
  All values not containing the given string.
  """
  password_not_contains: String
  """
  All values starting with the given string.
  """
  password_starts_with: String
  """
  All values not starting with the given string.
  """
  password_not_starts_with: String
  """
  All values ending with the given string.
  """
  password_ends_with: String
  """
  All values not ending with the given string.
  """
  password_not_ends_with: String
}

input UserWhereUniqueInput {
  id: ID
  email: String
}
```

When I run the following:

```javascript
const ultimateSchema = mergeTypes([
    readFileSync('./datamodel.graphql').toString(),
    readFileSync('./dataops.graphql').toString(),
    readFileSync('./generated/prisma.graphql').toString()
], {
    all: true
});
```

I get:

```
/home/lastmjs/development/prendus-app/backend/node_modules/merge-graphql-schemas/dist/index.cjs.js:4295
  return _addCommentsToAST(candidate.fields).reduce(function (fields, field) {
                                             ^
TypeError: Cannot read property 'value' of undefined
    at /home/lastmjs/development/prendus-app/backend/node_modules/merge-graphql-schemas/dist/index.cjs.js:4302:30
    at Array.reduce (<anonymous>)
    at _makeMergedFieldDefinitions (/home/lastmjs/development/prendus-app/backend/node_modules/merge-graphql-schemas/dist/index.cjs.js:4295:46)
    at defs.filter.reduce.Query (/home/lastmjs/development/prendus-app/backend/node_modules/merge-graphql-schemas/dist/index.cjs.js:4328:17)
    at Array.reduce (<anonymous>)
    at _makeMergedDefinitions (/home/lastmjs/development/prendus-app/backend/node_modules/merge-graphql-schemas/dist/index.cjs.js:4315:6)
    at Object.mergeTypes (/home/lastmjs/development/prendus-app/backend/node_modules/merge-graphql-schemas/dist/index.cjs.js:4367:20)
    at Object.<anonymous> (/home/lastmjs/development/prendus-app/backend/index.ts:14:24)
    at Module._compile (module.js:643:30)
    at Module.m._compile (/home/lastmjs/development/prendus-app/backend/node_modules/ts-node/src/index.ts:422:23)
```

I did a little digging into `index.cjs.js`, and here is the offending function:
```javascript
var _makeMergedFieldDefinitions = function _makeMergedFieldDefinitions(merged, candidate) {
  return _addCommentsToAST(candidate.fields).reduce(function (fields, field) {
    var original = merged.fields.find(function (base) {
      return base.name && typeof base.name.value !== 'undefined' && field.name && typeof field.name.value !== 'undefined' && base.name.value === field.name.value;
    });
    console.log(field.type.type);
    if (!original) {
      fields.push(field);
  } else if (field.type.name.value !== original.type.name.value) {
      throw new Error(`Conflicting types for ${merged.name.value}.${field.name.value}: ` + `${field.type.name.value} != ${original.type.name.value}`);
    }
    return fields;
  }, merged.fields);
};
```

The `else if` there is causing the problem. Changing it from `field.type.name.value` to `field.type.type.name.value` and `original.type.name.value` to `original.type.type.name.value` seems to do the trick.

**Comment by cfnelson** [comment]
@lastmjs Thanks for providing this feedback. I have tested your suggestion, however it breaks a few existing tests,

Check out the `merges query types with matching definitions` test [here](https://github.com/okgrow/merge-graphql-schemas/blob/master/test/merge_types.test.js#L139) for an example test and the types it tests against can be found [here](https://github.com/okgrow/merge-graphql-schemas/tree/master/test/graphql/other/custom_type). 

I am not to sure/clear on why there is `type.type` occurring for your prisma schema? Would you be able to show us what your `field.type` looks likes when this occurs.

I guess a simple solution/quick fix would be to check if `name` is defined on `field.type`.
e.g -> `field.type.name && original.type.name` and add an additional `else if` to support the situation you are describing.

**Comment by lastmjs** [comment]
Here you go, `field.type`:
```
{ kind: 'NonNullType',
  type: 
   { kind: 'NamedType',
     name: { kind: 'Name', value: 'ID', loc: [Object] },
     loc: { start: 142, end: 144 } },
  loc: { start: 142, end: 145 } }
```

**Comment by lastmjs** [comment]
I'll work on a PR

**Comment by cfnelson** [comment]
@lastmjs Thanks for that, with your changes does your schema build and run the way you expect? e.g Do your types get merged correctly or throw when there is a fieldDef with a type conflict?

**Comment by lastmjs** [comment]
I've only manually tested, but my schema compiles correctly and I can use GraphiQL to do all of the basic operations that I have tested

**Comment by lastmjs** [comment]
It looks like the issue was not accounting for `NonNullType` fields. Fixed the tests to account for that and made a fix to the code: https://github.com/okgrow/merge-graphql-schemas/pull/125

**Comment by lastmjs** [comment]
Merged! https://github.com/okgrow/merge-graphql-schemas/pull/125

**Comment by cfnelson** [comment]
@lastmjs Thanks again for this! Sorry it took so long to release. `v1.5.1` is now out on npm, I hope it fixes everything for you! :)

**Comment by tdharris** [comment]
@lastmjs, first of all, thank you so much for your work! I've been digging into your medium article, which is very insightful & helpful. I am discovering one small problem in the case of `NonNullType` fields with the following as my `field.type` (`v1.5.1`):
```
{ "kind": "NonNullType",
    "type": {
        "kind": "ListType",
        "type": {
            "kind": "NamedType",
            "name": {
                "kind": "Name",
                "value": "Application",
                "loc": {
                    "start": 51654,
                    "end": 51665
                }
            },
            "loc": {
                "start": 51654,
                "end": 51665
            }
        },
        "loc": {
            "start": 51653,
            "end": 51666
        }
    },
    "loc": {
        "start": 51653,
        "end": 51667
    }
}
```
So it looks like in this case, I suppose we would need `field.type.type.type.name.value` 🤣 
I'm not quite sure how much more nested things may get..? 😕
