### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined within NonNullType

### ISSUE THREAD

**Issue by tdharris** [okgrow/merge-graphql-schemas#140]
I am on `v1.5.1` and am discovering one small problem in a particular case of `NonNullType` fields (issue #124, fixed in #125). This fix did help resolve a previous problem (thank you!), but this new issue is a similar problem in the case of `NonNullType` only (as far as I can tell). 

I receive the following error:
```
node_modules/merge-graphql-schemas/dist/index.cjs.js:4296
  return _addCommentsToAST(candidate.fields).reduce(function (fields, field) {
                                             ^
TypeError: Cannot read property 'value' of undefined
    at /mnt/c/dev/sp-prisma/node_modules/merge-graphql-schemas/dist/index.cjs.js:4307:32
    at Array.reduce (<anonymous>)
    at _makeMergedFieldDefinitions (/mnt/c/dev/sp-prisma/node_modules/merge-graphql-schemas/dist/index.cjs.js:4296:46)
    at defs.filter.reduce.Query (/mnt/c/dev/sp-prisma/node_modules/merge-graphql-schemas/dist/index.cjs.js:4334:17)
    at Array.reduce (<anonymous>)
    at _makeMergedDefinitions (/mnt/c/dev/sp-prisma/node_modules/merge-graphql-schemas/dist/index.cjs.js:4321:6)
    at Object.mergeTypes (/mnt/c/dev/sp-prisma/node_modules/merge-graphql-schemas/dist/index.cjs.js:4373:20)
    at Object.<anonymous> (/mnt/c/dev/sp-prisma/src/index.ts:27:30)
    at Module._compile (module.js:662:30)
    at Module.m._compile (/mnt/c/dev/sp-prisma/node_modules/ts-node/src/index.ts:403:23)
```

The following is my `field.type`:
```
{   "kind": "NonNullType",
    "type": {
        "kind": "ListType",
        "type": {
            "kind": "NamedType",
            "name": {
                "kind": "Name",
                "value": "Application",
                "loc": {
                    "start": 51654,
                    "end": 51665
                }
            },
            "loc": {
                "start": 51654,
                "end": 51665
            }
        },
        "loc": {
            "start": 51653,
            "end": 51666
        }
    },
    "loc": {
        "start": 51653,
        "end": 51667
    }
}
```

So it looks like in this case, we would need `field.type.type.type.name.value` 🤣 
I'm not quite sure how nested things may get here, so am curious what the right approach might be..

Taking a peak in `index.cjs.js`, the following code change within `_makeMergedFieldDefinitions()` on `l 4306` resolves this issue for me: 
https://github.com/okgrow/merge-graphql-schemas/blob/b79816c63574eb899120ea435e24825d2100035a/src/merge_types.js#L64-L70
```
} else if (field.type.kind === 'NonNullType') {
    if (field.type.type.name) {
        if (field.type.type.name.value !== original.type.type.name.value) {
            throw new Error(
                `Conflicting types for ${merged.name.value}.${field.name.value}: ` + 
                `${field.type.type.name.value} != ${original.type.type.name.value}`
            );
        }
    } else if (field.type.type.type.name) {
        if (field.type.type.type.name.value !== original.type.type.type.name.value) {
            throw new Error(
                `Conflicting types for ${merged.name.value}.${field.name.value}: ` + 
                `${field.type.type.type.name.value} != ${original.type.type.type.name.value}`
            );
        }
    }
}
```

I am looking for some feedback if this may be the right approach here? If there is potential for another layer of `type`, this sort of change may just be kicking the can down the road. 😕

**Comment by RodMachado** [comment]
Hey @tdharris,

Do you mind sharing a snippet of the actual type that is causing this? I'm trying to replicate the problem.

Thanks!

**Comment by RodMachado** [comment]
@tdharris, could you also share how you are parsing the schemas? Are you using graphql's `buildSchema`, Apollo's `makeExecutableSchema`, or something else?

**Comment by tdharris** [comment]
Yah, of course! I only hope I have everything right here for ya. My apologies for the long comment here. Like #124, I receive this when working with Prisma (`graphql prepare`). I think I've simplified it to the following:

```graphql
# datamodel.graphql
type User {
  id: ID! @unique
  email: String!
}
```
```graphql
# app.graphql
directive @isAuthenticated on FIELD | FIELD_DEFINITION

type Query {
  users: [User]! @isAuthenticated
}
```
```graphql
# prisma.graphql
# THIS FILE HAS BEEN AUTO-GENERATED BY "PRISMA DEPLOY"
# DO NOT EDIT THIS FILE DIRECTLY

#
# Model Types
#

type User implements Node {
  id: ID!
  email: String!
}

#
# Other Types
#

type AggregateUser {
  count: Int!
}

type BatchPayload {
  """The number of nodes that have been affected by the Batch operation."""
  count: Long!
}

"""
The `Long` scalar type represents non-fractional signed whole numeric values.
Long can represent values between -(2^63) and 2^63 - 1.
"""
scalar Long

type Mutation {
  createUser(data: UserCreateInput!): User!
  updateUser(data: UserUpdateInput!, where: UserWhereUniqueInput!): User
  deleteUser(where: UserWhereUniqueInput!): User
  upsertUser(where: UserWhereUniqueInput!, create: UserCreateInput!, update: UserUpdateInput!): User!
  updateManyUsers(data: UserUpdateInput!, where: UserWhereInput): BatchPayload!
  deleteManyUsers(where: UserWhereInput): BatchPayload!
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
}

"""An object with an ID"""
interface Node {
  """The id of the object."""
  id: ID!
}

"""Information about pagination in a connection."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

type Query {
  users(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User]!
  user(where: UserWhereUniqueInput!): User
  usersConnection(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): UserConnection!

  """Fetches an object given its ID"""
  node(
    """The ID of an object"""
    id: ID!
  ): Node
}

type Subscription {
  user(where: UserSubscriptionWhereInput): UserSubscriptionPayload
}

"""A connection to a list of items."""
type UserConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [UserEdge]!
  aggregate: AggregateUser!
}

input UserCreateInput {
  email: String!
}

"""An edge in a connection."""
type UserEdge {
  """The item at the end of the edge."""
  node: User!

  """A cursor for use in pagination."""
  cursor: String!
}

enum UserOrderByInput {
  id_ASC
  id_DESC
  email_ASC
  email_DESC
  updatedAt_ASC
  updatedAt_DESC
  createdAt_ASC
  createdAt_DESC
}

type UserPreviousValues {
  id: ID!
  email: String!
}

type UserSubscriptionPayload {
  mutation: MutationType!
  node: User
  updatedFields: [String!]
  previousValues: UserPreviousValues
}

input UserSubscriptionWhereInput {
  """Logical AND on all given filters."""
  AND: [UserSubscriptionWhereInput!]

  """Logical OR on all given filters."""
  OR: [UserSubscriptionWhereInput!]

  """Logical NOT on all given filters combined by AND."""
  NOT: [UserSubscriptionWhereInput!]

  """
  The subscription event gets dispatched when it's listed in mutation_in
  """
  mutation_in: [MutationType!]

  """
  The subscription event gets only dispatched when one of the updated fields names is included in this list
  """
  updatedFields_contains: String

  """
  The subscription event gets only dispatched when all of the field names included in this list have been updated
  """
  updatedFields_contains_every: [String!]

  """
  The subscription event gets only dispatched when some of the field names included in this list have been updated
  """
  updatedFields_contains_some: [String!]
  node: UserWhereInput
}

input UserUpdateInput {
  email: String
}

input UserWhereInput {
  """Logical AND on all given filters."""
  AND: [UserWhereInput!]

  """Logical OR on all given filters."""
  OR: [UserWhereInput!]

  """Logical NOT on all given filters combined by AND."""
  NOT: [UserWhereInput!]
  id: ID

  """All values that are not equal to given value."""
  id_not: ID

  """All values that are contained in given list."""
  id_in: [ID!]

  """All values that are not contained in given list."""
  id_not_in: [ID!]

  """All values less than the given value."""
  id_lt: ID

  """All values less than or equal the given value."""
  id_lte: ID

  """All values greater than the given value."""
  id_gt: ID

  """All values greater than or equal the given value."""
  id_gte: ID

  """All values containing the given string."""
  id_contains: ID

  """All values not containing the given string."""
  id_not_contains: ID

  """All values starting with the given string."""
  id_starts_with: ID

  """All values not starting with the given string."""
  id_not_starts_with: ID

  """All values ending with the given string."""
  id_ends_with: ID

  """All values not ending with the given string."""
  id_not_ends_with: ID
  email: String

  """All values that are not equal to given value."""
  email_not: String

  """All values that are contained in given list."""
  email_in: [String!]

  """All values that are not contained in given list."""
  email_not_in: [String!]

  """All values less than the given value."""
  email_lt: String

  """All values less than or equal the given value."""
  email_lte: String

  """All values greater than the given value."""
  email_gt: String

  """All values greater than or equal the given value."""
  email_gte: String

  """All values containing the given string."""
  email_contains: String

  """All values not containing the given string."""
  email_not_contains: String

  """All values starting with the given string."""
  email_starts_with: String

  """All values not starting with the given string."""
  email_not_starts_with: String

  """All values ending with the given string."""
  email_ends_with: String

  """All values not ending with the given string."""
  email_not_ends_with: String
}

input UserWhereUniqueInput {
  id: ID
}
```

When running the following:
```js
const ultimateSchemaString = mergeTypes([
    readFileSync('./datamodel.graphql').toString(),
    readFileSync('./app.graphql').toString(),
    readFileSync('./prisma.graphql').toString()
], {
    all: true 
});
```

I get the following error:
```
.../node_modules/merge-graphql-schemas/dist/index.cjs.js:4296
  return _addCommentsToAST(candidate.fields).reduce(function (fields, field) {
                                             ^
TypeError: Cannot read property 'value' of undefined
    at .../node_modules/merge-graphql-schemas/dist/index.cjs.js:4310:34
    at Array.reduce (<anonymous>)
    at _makeMergedFieldDefinitions (.../node_modules/merge-graphql-schemas/dist/index.cjs.js:4296:46)
    at defs.filter.reduce.Query (.../node_modules/merge-graphql-schemas/dist/index.cjs.js:4342:17)
    at Array.reduce (<anonymous>)
    at _makeMergedDefinitions (.../node_modules/merge-graphql-schemas/dist/index.cjs.js:4329:6)
    at Object.mergeTypes (.../node_modules/merge-graphql-schemas/dist/index.cjs.js:4381:20)
    at Object.<anonymous> (.../src/index.ts:45:30)
    at Module._compile (module.js:662:30)
    at Module.m._compile (.../node_modules/ts-node/src/index.ts:403:23)
```

Here is `field.type` and `original` in the context of `_makeMergedFieldDefinitions()`:
```json
field.type: {
    "kind": "NonNullType",
    "type": {
        "kind": "ListType",
        "type": {
            "kind": "NamedType",
            "name": {
                "kind": "Name",
                "value": "User",
                "loc": {
                    "start": 1571,
                    "end": 1575
                }
            },
            "loc": {
                "start": 1571,
                "end": 1575
            }
        },
        "loc": {
            "start": 1570,
            "end": 1576
        }
    },
    "loc": {
        "start": 1570,
        "end": 1577
    }
}

original: {
    "kind": "FieldDefinition",
    "name": {
        "kind": "Name",
        "value": "users",
        "loc": {
            "start": 376,
            "end": 381
        }
    },
    "arguments": [],
    "type": {
        "kind": "NonNullType",
        "type": {
            "kind": "ListType",
            "type": {
                "kind": "NamedType",
                "name": {
                    "kind": "Name",
                    "value": "User",
                    "loc": {
                        "start": 384,
                        "end": 388
                    }
                },
                "loc": {
                    "start": 384,
                    "end": 388
                }
            },
            "loc": {
                "start": 383,
                "end": 389
            }
        },
        "loc": {
            "start": 383,
            "end": 390
        }
    },
    "directives": [{
        "kind": "Directive",
        "name": {
            "kind": "Name",
            "value": "isAuthenticated",
            "loc": {
                "start": 392,
                "end": 407
            }
        },
        "arguments": [],
        "loc": {
            "start": 391,
            "end": 407
        }
    }],
    "loc": {
        "start": 376,
        "end": 407
    }
}
```
And changing the `NonNullType` condition to the approach provided earlier resolves this for me - https://github.com/okgrow/merge-graphql-schemas/issues/140#issue-321293548.

**Comment by atten** [comment]
Any progress with it?

**Comment by tdharris** [comment]
It looks like it wasn't accounting for `ListType` in `NonNullType` fields. I made a fix to the code and added a test for this: #161

**Comment by lastmjs** [comment]
Should this issue be closed now?

**Comment by tdharris** [comment]
Yah, thanks for the reminder!
https://github.com/okgrow/merge-graphql-schemas/pull/161
